version: '3'
services:
  pen-server:
    build: .
    image: pentaho_server_ce:9.3
    container_name: pentaho-server
    networks:
      - pentaho_hub
    restart: always
    ports:
      - "8081:8080"
        #    volumes:
        #      - ./data/hsqldb:/opt/pentaho/pentaho-server/data/hsqldb:rw #Schedule/Quartz/hibernate
        #      - ./data/jackrabbit-repository:/opt/pentaho/pentaho-server/pentaho-solutions/system/jackrabbit/repository:rw #login, bancos, JOB, TR
        #      - ./logs:/opt/pentaho/pentaho-server/tomcat/logs
    environment:
      - TZ=Europe/Moskow
networks:
  pentaho_hub:
    external:
      name: network_pentaho
